services:
  scd-2:
#    depends_on:
#      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - DATABASE=host.docker.internal
    image: "postgres:15"
    command:
      - /bin/bash
      - -c 
      - | 
        set -e
        sleep 5 # postgres is not up at 0
        psql -v ON_ERROR_STOP=1 --username $${PGUSER} --dbname postgres --host $${DATABASE} --port 5432 <<EOSQL
        -- drop
        drop table if exists test_data;
        drop table if exists test_data_history;
        
        -- create
        create table test_data (id serial PRIMARY KEY, amount numeric(12,8), curveStart TIMESTAMP);
        create table test_data_history (id serial, amount numeric(12,8), curveStart TIMESTAMP, curveEnd TIMESTAMP);
        CREATE INDEX ON test_data_history (id); -- this has to be updated?

        -- insert initial data (no history yet)
        insert into test_data (amount, curveStart) values (1.0, TO_TIMESTAMP('6/1/2022', 'MM/DD/YYYY'));

        -- confirm 1 (brand new world)
        select * from test_data;

        -- update (via scd2)
        \set _currenttime NOW() -- this is when the update is happening
        with data as (
            select * from test_data where id = '1'
        ),
        update as (
            insert into test_data_history (id, amount, curveStart, curveEnd)
            select id, amount, curveStart, :_currenttime
            from data
        )
        update test_data set amount = 2.0, curveStart = :_currenttime where id = 1;
        -- confirm 3
        select * from test_data;
        select * from test_data_history;

        -- 2nd update (via scd2)
        \set _currenttime2 NOW()
        with data as (
            select * from test_data where id = '1' -- index whatever fields we are using
        ),
        update as (
            insert into test_data_history (id, amount, curveStart, curveEnd)
            select id, amount, curveStart, :_currenttime2
            from data
        )
        update test_data set amount = 3.0 where id = 1;

        -- confirm 3
        select * from test_data;
        select * from test_data_history;

        -- TODO -- failure txs/rollback sql
        -- TODO -- covert to panda
        -- TODO -- failure txs/rollback panda
        EOSQL