FROM python:3.11-bullseye
WORKDIR /
COPY /src/requirements.txt /src/requirements.txt
COPY /src/trueprice-api.py /src/trueprice-api.py
RUN pip install --no-cache-dir -r /src/requirements.txt
ENTRYPOINT flask --app /src/trueprice-api run --host=0.0.0.0