FROM python:3.11-bullseye
WORKDIR /
RUN mkdir /flask_file_upload
COPY /src/requirements.txt /src/requirements.txt
COPY /src/trueprice_database.py /src/trueprice_database.py
COPY /src/trueprice_api.py /src/trueprice_api.py
COPY /src/ingestor.py /src/ingestor.py
RUN pip install --no-cache-dir -r /src/requirements.txt
ENTRYPOINT flask --app /src/trueprice_api run --host=0.0.0.0